### ISSUE TITLE
[Request] coco17-val.txt

### ISSUE THREAD

**Issue by naoto0804** [VisionLearningGroup/visda-2018-public#2]
Thank you for releasing the codes!

https://github.com/VisionLearningGroup/visda-2018-public/blob/master/detection/pytorch-ssd-mmd-coral/train_visda_source.py#L77
Like this, all of the scripts assume the existence of `coco17-val.txt`.
Is it possible to share `coco17-val.txt` in addition to `coco17-val-names.txt`?
Or, should I extract it manually?

**Comment by MInner** [comment]
@naoto0804 , sorry for inconvenience and thank you for reporting it! I though we could have more intrigue  by not releasing it, but it seems that indeed starting code is too coupled with it. Feel free to `wget` from  `http://csr.bu.edu/ftp/visda/2018/detection/coco17-val.txt`

**Comment by naoto0804** [comment]
Thank you so much!
