### ISSUE TITLE
Have not noticed the deadline of submitting the form.

### ISSUE THREAD

**Issue by lianqing11** [VisionLearningGroup/visda-2018-public#21]
Dear Visda organizers,

     I have not noticed that we need to submit the google form https://goo.gl/forms/G6Kl7OuUVg1BvbRu1  before Aug 25th, I am wonder if i still can submit this form?
   
    Sorry for my carelessness, hope you can give me this chance.

Best Regards,
Qing Lian

**Comment by youkaichao** [comment]
@lianqing11  do you have any solution? why do you close this issue?

**Comment by lianqing11** [comment]
@youkaichao Visda's orginiazor told me it is still valid to submit the form.

**Comment by youkaichao** [comment]
@lianqing11  what's the deadline to submit the form?

**Comment by youkaichao** [comment]
@xcpeng  I wonder what is the difference between Team Name and Username for Codalab? Current leaderboard only displays username and the form mentioned above asks for Team Name, how do organizers map Team Name and Username?

**Comment by lianqing11** [comment]
@youkaichao  Sorry, i am also not quite sure. Maybe we can ask the orginiazor?

**Comment by xcpeng** [comment]
Hi,

We have the metadata for all participants and we will match the user name
and tema name.
