### ISSUE TITLE
Detection competition - unable to submit predictions to CodaLab

### ISSUE THREAD

**Issue by Britefury** [VisionLearningGroup/visda-2018-public#9]
Hi,

I've been having difficult submitting to the detection competition. It appears that my text file format is incorrect, as I get the following error:

```
Traceback (most recent call last):
  File "/tmp/codalab/tmpxfH0zT/run/program/evaluate.py", line 438, in 
    detection_evaluation(truth_file, source_file, adaptation_file, output_file)
  File "/tmp/codalab/tmpxfH0zT/run/program/evaluate.py", line 363, in detection_evaluation
    for line in f.read().splitlines()
  File "/tmp/codalab/tmpxfH0zT/run/program/evaluate.py", line 21, in chunks
    raise RuntimeError("Sequence does not split into {k}, because last elem has {elem.index(uniq)} left")
RuntimeError: Sequence does not split into {k}, because last elem has {elem.index(uniq)} left
```

Would it be possible for you guys to either:

- provide an example submission file that the server can handle
- provide code to generate a valid submission file
- provide the source code of 'evaluate.py' that runs on the server
- modify the evaluation code so that it reports more helpful error messages

Thanks! :)

**Comment by Britefury** [comment]
Thanks!
Figured out my mistake.

**Comment by MInner** [comment]
Just to clarify, `*.pkl` file is just a "precomputed cached" bbox data inferred from gt files and images provided previously.

**Comment by Britefury** [comment]
Referring to the other issue (https://github.com/VisionLearningGroup/visda-2018-public/issues/10) the `pkl` file loads fine using the `pickle` module. The bbox values in the `pkl` file are scaled when compared to those in `coco17-val.txt`.
